import { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: 1,
    slug: "fresh-bananas",
    name: "Fresh Bananas",
    category: "Fruits",
    description: "Fresh farm bananas rich in potassium.",
    image: "/images/products/banana.png",
    price: 49,
    mrp: 60,
    discount: 18,
    rating: 4.8,
    reviews: 254,
    stock: 40,
    unit: "1 dozen",
    deliveryTime: "10 mins",
    featured: true,
    bestseller: true,
  },

  {
    id: 2,
    slug: "red-apples",
    name: "Red Apples",
    category: "Fruits",
    description: "Premium Kashmiri apples.",
    image: "/images/products/apple.png",
    price: 179,
    mrp: 220,
    discount: 19,
    rating: 4.7,
    reviews: 193,
    stock: 28,
    unit: "1 kg",
    deliveryTime: "10 mins",
    featured: true,
    bestseller: false,
  },

  {
    id: 3,
    slug: "amul-milk",
    name: "Amul Milk",
    category: "Dairy",
    description: "Fresh toned milk.",
    image: "/images/products/milk.png",
    price: 34,
    mrp: 36,
    discount: 5,
    rating: 4.9,
    reviews: 540,
    stock: 100,
    unit: "500 ml",
    deliveryTime: "8 mins",
    featured: true,
    bestseller: true,
  },

  {
    id: 4,
    slug: "brown-bread",
    name: "Brown Bread",
    category: "Bakery",
    description: "Healthy whole wheat bread.",
    image: "/images/products/bread.png",
    price: 45,
    mrp: 55,
    discount: 18,
    rating: 4.6,
    reviews: 142,
    stock: 32,
    unit: "400 g",
    deliveryTime: "12 mins",
    featured: false,
    bestseller: false,
  },

  {
    id: 5,
    slug: "lays-chips",
    name: "Lay's Chips",
    category: "Snacks",
    description: "Classic salted potato chips.",
    image: "/images/products/chips.png",
    price: 20,
    mrp: 20,
    discount: 0,
    rating: 4.7,
    reviews: 810,
    stock: 250,
    unit: "52 g",
    deliveryTime: "8 mins",
    featured: false,
    bestseller: true,
  },

  {
    id: 6,
    slug: "coca-cola",
    name: "Coca Cola",
    category: "Beverages",
    description: "Chilled soft drink.",
    image: "/images/products/coke.png",
    price: 40,
    mrp: 45,
    discount: 11,
    rating: 4.5,
    reviews: 301,
    stock: 80,
    unit: "750 ml",
    deliveryTime: "8 mins",
    featured: false,
    bestseller: false,
  },

  {
    id: 7,
    slug: "fresh-tomatoes",
    name: "Fresh Tomatoes",
    category: "Vegetables",
    description: "Farm fresh tomatoes.",
    image: "/images/products/tomato.png",
    price: 35,
    mrp: 45,
    discount: 22,
    rating: 4.6,
    reviews: 201,
    stock: 50,
    unit: "1 kg",
    deliveryTime: "10 mins",
    featured: true,
    bestseller: false,
  },

  {
    id: 8,
    slug: "onions",
    name: "Onions",
    category: "Vegetables",
    description: "Premium quality onions.",
    image: "/images/products/onion.png",
    price: 32,
    mrp: 40,
    discount: 20,
    rating: 4.5,
    reviews: 173,
    stock: 70,
    unit: "1 kg",
    deliveryTime: "10 mins",
    featured: false,
    bestseller: false,
  }
];